// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe4sIIA_iixuVMEnETREx8SNPomQeeHgs',
    appId: '1:123466091433:web:6ba233bce1fc189818d2b8',
    messagingSenderId: '123466091433',
    projectId: 'crud-firebase-d4424',
    authDomain: 'crud-firebase-d4424.firebaseapp.com',
    storageBucket: 'crud-firebase-d4424.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGggC8hr6cYJLIRYRNwnXwJchTYqAuS5A',
    appId: '1:123466091433:android:66570686cd53849818d2b8',
    messagingSenderId: '123466091433',
    projectId: 'crud-firebase-d4424',
    storageBucket: 'crud-firebase-d4424.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqoTy3hoVrpSedM-HFht1C93FtqBvxwMo',
    appId: '1:123466091433:ios:af483e5bd59062a718d2b8',
    messagingSenderId: '123466091433',
    projectId: 'crud-firebase-d4424',
    storageBucket: 'crud-firebase-d4424.appspot.com',
    iosBundleId: 'com.example.flutterApplication1Crudf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqoTy3hoVrpSedM-HFht1C93FtqBvxwMo',
    appId: '1:123466091433:ios:af483e5bd59062a718d2b8',
    messagingSenderId: '123466091433',
    projectId: 'crud-firebase-d4424',
    storageBucket: 'crud-firebase-d4424.appspot.com',
    iosBundleId: 'com.example.flutterApplication1Crudf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe4sIIA_iixuVMEnETREx8SNPomQeeHgs',
    appId: '1:123466091433:web:f99ff7758d6ceea618d2b8',
    messagingSenderId: '123466091433',
    projectId: 'crud-firebase-d4424',
    authDomain: 'crud-firebase-d4424.firebaseapp.com',
    storageBucket: 'crud-firebase-d4424.appspot.com',
  );
}
